### PR TITLE
Various fixes and updates over the Debian packaging

### PR DESCRIPTION
**Pull request by fbriere**
With these changes, the Debian packaging (which is currently broken) now builds successfully for Python 3 from `stretch` (`oldstable`) onwards, and is Lintian-clean to boot.

(I initially thought about splitting `liblarch_gtk` into its own package, to allow installing the non-GTK module on its own with fewer dependencies, but this isn't easily supported by `pybuild`.)

### CODE REVIEW

**Comment by nekohayo** [comment]
Damn, I hadn't seen this pull request and had made commit 4d1a7dfa3e making changes in the debian/control file's description to fix some typos, barely a day after you, causing a conflict with your merge request. I'll have to try to resolve it first (unless you beat me to the punch).

**Comment by fbriere** [comment]
> I'll have to try to resolve it first (unless you beat me to the punch).

Challenge accepted!  :smirk:

**Comment by nekohayo** [comment]
Vous m'en voyez ravi !

Well these changes look clean and neat and easily mergeable!
Just a question I forgot to ask, though: as you may have noticed there has been at least a couple of little fixes committed in liblarch since its "3.0" tagged release, which would mean I'd have to make a release commit and tag it 3.0.1 or something like that. Would your changes need to be re-changed (to reflect the new release) after that happens, or right now/before, or...? Just giving a heads up in case this changes anything to this merge request, otherwise if it doesn't influence it then let me know and I'd merge it as-is.

**Comment by fbriere** [comment]
> as you may have noticed there has been at least a couple of little fixes committed in liblarch since its "3.0" tagged release

That's why I opted for a temporary version number (`v3.0-26-g2b3366b-1`) based on `git describe`, to avoid any confusion until the next official release.

> Would your changes need to be re-changed (to reflect the new release) after that happens, or right now/before, or...?

When updating `setup.py` for the release commit, simply switch the version number in `debian/changelog` (with `3.0.1-1` in your example), and ideally replace "New upstream snapshot" with "New upstream release".  Then everything will be, as we both would say, "tiguidou".  :smile:

**Pull request merged**
