### PR TITLE
Slight optimization on refilter/apply_filter

### PR DESCRIPTION
**Pull request by jaesivsm**
* accounting for `refresh` parameters without changing default behavior
* removing useless cast to list (actually slowing search in `add_to`)
* shortening `self.fbank` browsing

### CODE REVIEW

**Comment by ploum** [comment]
Does it pass unit tests ?

**Comment by jaesivsm** [comment]
```bash
make check 
./run-tests
....................................................................
----------------------------------------------------------------------
Ran 68 tests in 6.840s

OK
```

Testing and linting :)

**Comment by ploum** [comment]
Awesome. Changes looks good to me. I'm only worried about the "refresh=True". It looks like it changes the default behaviour.

I'll let @diegogangl or @nekohayo merge it.

**Comment by jaesivsm** [comment]
Well the `refresh` var from the function definition wasn't used at all. So the basic behavior was just to ignore the value entirely. 
The only calls I saw were specifying `refresh=False` (which of course, was also ignored). 
I made it so the default behavior (without specifying anything in the call) does not change at all.

All in all, the merge should be safe.

**Comment by ploum** [comment]
Thanks for the explanation. Then, it's all good for me !

**Comment by nekohayo** [comment]
Thanks for taking a look Ploum!

If by chance @diegogangl or @neui would also like (and have time) to take a quick look at this merge request, that would be awesome, because they also had some interest in performance optimizations and I'd trust them more than me to actually understand what's going on in this code :)

**Comment by Neui** [comment]
Changes look good, and similar changes I once did to try out if it does any (performance) improvements, but it didn't really do anything. I even went the extra mile to convert the direction to an integer to prevent comparing strings (but from what I've recently read about, python has [string interning](https://stackabuse.com/guide-to-string-interning-in-python/) which also should be fast to compare strings, but I didn't check)

The `refresh` in it self also looks good (allowing to delay filtering), but this possibly breaks some behaviour where `refresh=False` is specified. However, I just looked at all instances of `apply_filter` in liblarch and GTG (not that many), and they seem "correct" (they are refiltered later as needed), so this should be fine.

**Review by Neui — APPROVED** [review]
Changes look good, and similar changes I once did to try out if it does any (performance) improvements, but it didn't really do anything. I even went the extra mile to convert the direction to an integer to prevent comparing strings (but from what I've recently read about, python has [string interning](https://stackabuse.com/guide-to-string-interning-in-python/) which also should be fast to compare strings, but I didn't check)

The `refresh` in it self also looks good (allowing to delay filtering), but this possibly breaks some behaviour where `refresh=False` is specified. However, I just looked at all instances of `apply_filter` in liblarch and GTG (not that many), and they seem "correct" (they are refiltered later as needed), so this should be fine.

**Comment by nekohayo** [comment]
I gave this a quick try, and did not see immediately breaking changes; I saw a bug but that's probably due to the changes in GTG itself in @jaesivsm's branch at https://github.com/getting-things-gnome/gtg/pull/530 so will presume this liblarch change is OK... but just in case maybe I'll wait a bit before merging this, in case the changes downstream require further changes here in liblarch?

**Comment by nekohayo** [comment]
Merged/pushed to master, as the fix has been tested by multiple folks and proven to work on GTG without further changes required in this liblarch patch, so I assume it's all good!

**Pull request closed without merging**
